// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_fCoBOMcGjyIlCl-YJfPCnWI4o8ChbqY',
    appId: '1:1026058783113:web:dae82a591d918cea903958',
    messagingSenderId: '1026058783113',
    projectId: 'apps-79374',
    authDomain: 'apps-79374.firebaseapp.com',
    storageBucket: 'apps-79374.firebasestorage.app',
    measurementId: 'G-6FTYJRLJEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7DnlsmPtMO7aqnTNMfgYReTzFEYeprjQ',
    appId: '1:1026058783113:android:74c6141ac7996d9d903958',
    messagingSenderId: '1026058783113',
    projectId: 'apps-79374',
    storageBucket: 'apps-79374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbmnNkB8bTTUhWOHqRGxmGbUcniKHD_kw',
    appId: '1:1026058783113:ios:27b38ac2644670bb903958',
    messagingSenderId: '1026058783113',
    projectId: 'apps-79374',
    storageBucket: 'apps-79374.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbmnNkB8bTTUhWOHqRGxmGbUcniKHD_kw',
    appId: '1:1026058783113:ios:27b38ac2644670bb903958',
    messagingSenderId: '1026058783113',
    projectId: 'apps-79374',
    storageBucket: 'apps-79374.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_fCoBOMcGjyIlCl-YJfPCnWI4o8ChbqY',
    appId: '1:1026058783113:web:4e8ae28cb462c69b903958',
    messagingSenderId: '1026058783113',
    projectId: 'apps-79374',
    authDomain: 'apps-79374.firebaseapp.com',
    storageBucket: 'apps-79374.firebasestorage.app',
    measurementId: 'G-CJ6Y4CPZM5',
  );
}
